### ISSUE TITLE
Secret not deployed

### ISSUE THREAD

**Issue by diamondburned** [DBCDK/morph#78]
`deployment.secrets`:

```nix
deployment = {
	secrets = {
 		"shihoya-key" = {
			source = "./secrets/shihoya-key";
			destination = "/var/shihoya-key";
			owner = {
				user = "shihoya";
				group = "shihoya";
			};
			permissions = "0400";
			action = [ "sudo" "systemctl" "restart" "shihoya-api" ];
		};
	};
};
```

Deployed node:

```
[root@ceris-cbt:~]# ls -a /var
.  ..  cache  db  empty  lib  lock  log  run  spool  tmp  .updated
```

Host:

```
► ./secrets 
shihoya-key      shihoya-key.pub  
```

`morph` saw the secrets as well:

```
Selected 1/1 hosts (name filter:-0, limits:-0):
	  0: root@ec2.compute.amazonaws.com (secrets: 1, health checks: 0)
```

**Comment by johanot** [comment]
Thanks for reporting. Secret upload is not active by default in the deploy sequence, see #79. I believe #41 is related too, because once we implement secret diff'ing, we could make a "smart" decision on whether to upload secrets or not. However, until then, we've made the choice not to upload secrets for every deploy action unless explicitly commanded. :)
