### ISSUE TITLE
Custom host for deployment.healthChecks.http

### ISSUE THREAD

**Issue by diamondburned** [DBCDK/morph#80]
Something like

```nix
http = [
    {
        host = "127.0.0.1";
        ...
    }
];
```

Reason being for some hosts such as AWS, using the long EC2 address is typical, though they're never used in actual webservers. It would make more sense to feed the actual domain in or localhost. 

(Actual domain may not work, as some are reverse proxied over CloudFlare as well)

**Comment by adamtulinius** [comment]
Hi,

> Reason being for some hosts such as AWS, using the long EC2 address is typical, though they're never used in actual webservers. It would make more sense to feed the actual domain in or localhost.

I must confess I know next to nothing about AWS. Can you elaborate on what the problem is?

It is already possible to override the host-name used in HTTP-based health checks using the `host` attribute. Just note that HTTP-based health checks are evaluated on the host from where `morph` is run, unlike CMD-based health checks, which are run on the remote host.
